package br.com.eds.api.eds.model.software;

public enum TipoServicoSoftware {
    INSTACACAO_WINDOWS,
    INTALACAO_LINUX,
    INTALACAO_MAC,
    FORMATAÇÃO,
    BACKUP,
    OTIMIZACAO,
    PROBLEMAS_VIRUS,
    PACOTE_OFFICE,
    SEGURANCA,
    ATUALIZACAO_DRIVERS,
    RECUPERACAO_MEMORIA,
    ATUALIZAÇÃO_SISTEMA,
    MONTAGEM_MANUTENCAO_REDE,
    OUTRO
}
