package br.com.eds.api.eds.model.impressao;

public enum MaterialImpressao {
    PAPEL_SULFITE_75G,
    PAPEL_MONOLUCIDO_90G,
    PAPEL_FOTOGRAFICO_ADESIVO_130G,
    PAPEL_FOTOGRAFICO_180G,
    PAPEL_OFFSET_180G,
    PAPEL_OPALINE_240G,
    PAPEL_CANSON_240G,
    PAPEL_CANSON_300G,
    CALENDARIO,
    PAPEL_FOTOGRAFICO_DUPLA_FACE_180G
}
